language: go
go:
- 1.x
- '1.8'
- 1.10.x
- master
script:
- go build
deploy:
  provider: heroku
  api_key:
    secure: tlSNYrL5zf8umXqybb4hC1PVqH2BKwViZjxYrJmN9SREknFmqEkLCrFcrrFQ5ygJ2Tf9zLNm7hG/3P5g4NlwVbY0vwGiHUB/1J7/tfcvo2LOcxl666vHWdA9nUTH8CJ7W+a0WVn4sdWxZUjAdna+8eKWwcPLzLF2wi8cq4r72nKtAd9RLsafT/ASRuiw3T+tKZ6mEa204D6GJ8M5UQru2UmYqy5jOKEDiy6ktFo33BijZgpuGBvz3wPISCQYiiXZnJcDsb/RC4WG/AIL2R57Mzyx1d0JJ3pENsdEI8tKJs5kB8Z6k60Q3Nowi8CWs+B/eCULGG9sk9nNkGsk/x5NveFbkhlVwhwKCWCK+Voa68+N7xl9cMb0eGNVX4i6F4D/l7t4hrtvF824WVm1Eyts+xMjRg0k1idqEN7FWeVEfbyJPnTqufRm9JDNXFHE7O5JWuIpVJ/8UQjwiD5DpP+f7zG8X0oqoigEXQBkFwypOmn3m8tk9tABOaFx5S1drP3TktUxQz2OZix6rtpySpTNrWvGSnFcS18gd1OfJqR2G5hUlb+iFIkndIJ3HFPvQmaTn5fQcZFGhFw1LNizUymIE3w+NYuM3y0NAGGzMbY84Hz6aeHPA5/9MqgYifryVx9jETg8gmkSvF+CDUUwAUvsa+lEKgUBvcWyDRmzPWuq2/0=
  app: quiet-garden-65954
